export const auth = {
  PASSWORD_MIN_LEN: 6,
  PASSWORD_MAX_LEN: 50,
};

export const category = {
  NAME_MIN_LEN: 3,
  NAME_MAX_LEN: 30,
};

export const recipe = {
  TITLE_MIN_LEN: 3,
  TITLE_MAX_LEN: 50,
  SUMMARY_MAX_LEN: 300,
  NEEDED_TIME_MAX_LEN: 20,
  PORTIONS_MIN: 1,
  INSTRUCTION_MIN_LEN: 3,
  INSTRUCTION_MAX_LEN: 3000,
  INGREDIENT_MIN_LEN: 3,
  INGREDIENT_MAX_LEN: 30,
};
